In [2]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

In [3]:
password = urllib.parse.quote_plus("N@ndini2005")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/ecommerce_db"
)

conn = engine.connect()
print("CONNECTED ✅")
conn.close()

CONNECTED ✅

In [4]:
df = pd.read_sql("SELECT * FROM customer_behavior_cleaned", engine)

print("Shape:", df.shape)
df.head()

Shape: (1000000, 63)

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,...,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate,age_group,income_band,engagement_score
0,1,56,female,germany,suburban,90860,self-employed,associate degree,single,0,...,7,74,19,2025-06-22,6,1,50,51+,medium,7
1,2,69,male,japan,suburban,35423,unemployed,bachelor,single,1,...,5,23,8,2026-07-25,3,0,37,51+,low,12
2,3,46,female,india,urban,21467,self-employed,associate degree,married,1,...,7,12,13,2026-02-26,6,0,53,36-50,low,6
3,4,32,male,canada,urban,41770,self-employed,bachelor,widowed,0,...,4,19,9,2026-10-27,7,0,98,26-35,low,3
4,5,60,female,japan,urban,183882,employed,associate degree,widowed,1,...,7,30,3,2026-06-23,3,0,86,51+,high,23

In [5]:
# High engagement flag
df["high_engagement"] = df["engagement_score"] > df["engagement_score"].median()

# Customer segment logic
df["customer_segment"] = df.apply(
    lambda row: "target_segment"
    if row["age_group"] == "26-35" and row["high_engagement"]
    else "general_segment",
    axis=1
)

df["customer_segment"].value_counts()

customer_segment
general_segment    920162
target_segment      79838
Name: count, dtype: int64

In [6]:
import numpy as np

In [7]:
median_value = df["impulse_buying_score"].median()

df["recommended_category"] = np.where(
    df["impulse_buying_score"] > median_value,
    "electronics",
    "home_appliances"
)

In [8]:
df[["impulse_buying_score", "recommended_category"]].head()

   impulse_buying_score recommended_category
0                     1      home_appliances
1                     3      home_appliances
2                     2      home_appliances
3                     2      home_appliances
4                     8          electronics

In [9]:
output_path = "../data/customer_behavior_final.csv"

df.to_csv(
    output_path,
    index=False
)

print("CSV saved ✅")

CSV saved ✅

In [11]:
df.head(10000).to_sql(
    "customer_behavior_final",
    engine,
    if_exists="replace",
    index=False
)

100

In [12]:
df.to_sql(
    "customer_behavior_final",
    engine,
    if_exists="replace",
    index=False,
    chunksize=20000,
    method="multi"
)

1000000

In [13]:
pd.read_sql("SELECT COUNT(*) FROM customer_behavior_final", engine)

     count
0  1000000

In [14]:
df_final = pd.read_sql("SELECT * FROM customer_behavior_final", engine)
df_final.head()

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,...,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate,age_group,income_band,engagement_score,high_engagement,customer_segment,recommended_category
0,1,56,female,germany,suburban,90860,self-employed,associate degree,single,0,...,2025-06-22,6,1,50,51+,medium,7,False,general_segment,home_appliances
1,2,69,male,japan,suburban,35423,unemployed,bachelor,single,1,...,2026-07-25,3,0,37,51+,low,12,False,general_segment,home_appliances
2,3,46,female,india,urban,21467,self-employed,associate degree,married,1,...,2026-02-26,6,0,53,36-50,low,6,False,general_segment,home_appliances
3,4,32,male,canada,urban,41770,self-employed,bachelor,widowed,0,...,2026-10-27,7,0,98,26-35,low,3,False,general_segment,home_appliances
4,5,60,female,japan,urban,183882,employed,associate degree,widowed,1,...,2026-06-23,3,0,86,51+,high,23,True,general_segment,electronics

In [15]:
segment_distribution = df_final["customer_segment"].value_counts(normalize=True) * 100
segment_distribution

customer_segment
general_segment    92.0162
target_segment      7.9838
Name: proportion, dtype: float64

In [16]:
df_final.groupby("customer_segment")["engagement_score"].mean()

customer_segment
general_segment    13.144588
target_segment     17.645094
Name: engagement_score, dtype: float64

In [17]:
df_final["recommended_category"].value_counts()

recommended_category
home_appliances    545613
electronics        454387
Name: count, dtype: int64

In [18]:
summary = df_final.groupby("customer_segment").agg({
    "engagement_score": "mean",
    "impulse_buying_score": "mean",
    "income_level": "mean"
})

summary

                  engagement_score  impulse_buying_score   income_level
customer_segment
general_segment          13.144588              4.853267  105001.119936
target_segment           17.645094              6.671397  104919.022771

In [19]:
summary.to_sql(
    "customer_segment_summary",
    engine,
    if_exists="replace"
)

2